### ISSUE TITLE
nil pointer derefence in log

### ISSUE THREAD

**Issue by trisberg** [projectriff/topic-controller#5]
Running on GKE "v1.8.2-gke.0" produced the following:

```
$ k logs po/demo-sk8s-topic-controller-79445c46df-gvq5v
2017/11/16 19:37:31 Connected to 10.55.243.29:2181
E1116 19:37:31.105364       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:509
/usr/lib/go/src/runtime/panic.go:491
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:367
/root/go/src/github.com/sk8sio/topic-controller/cmd/topic-controller.go:84
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:192
<autogenerated>:1
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:311
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:147
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/lib/go/src/runtime/asm_amd64.s:2337
E1116 19:37:31.106062       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:509
/usr/lib/go/src/runtime/panic.go:491
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58
/usr/lib/go/src/runtime/asm_amd64.s:509
/usr/lib/go/src/runtime/panic.go:491
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:367
/root/go/src/github.com/sk8sio/topic-controller/cmd/topic-controller.go:84
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:192
<autogenerated>:1
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:311
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:147
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/lib/go/src/runtime/asm_amd64.s:2337
panic: 2017/11/16 19:37:31 Authenticated: id=99015697762811914, timeout=4000
runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x564d5213a5c5]

goroutine 15 [running]:
github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x113
panic(0x564d526ec060, 0x564d52fddc60)
	/usr/lib/go/src/runtime/panic.go:491 +0x287
github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x113
panic(0x564d526ec060, 0x564d52fddc60)
	/usr/lib/go/src/runtime/panic.go:491 +0x287
main.main.func1(0x564d5282a860, 0xc420020c00)
	/root/go/src/github.com/sk8sio/topic-controller/cmd/topic-controller.go:84 +0xa5
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc42023c050, 0x564d52861d38, 0x564d52861d30, 0x564d5282a860, 0xc420020c00)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:192 +0x4b
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc4201580a0, 0x564d5282a860, 0xc420020c00)
	<autogenerated>:1 +0x64
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x564d52702cc0, 0xc420314780, 0x564d52702cc0, 0xc420314780)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:311 +0x1aa
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc420150000, 0xc4201571d0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x26a
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc4201dc200)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x42
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2c
github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4205b0fb0)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x60
github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420277fb0, 0x3b9aca00, 0x0, 0x564d52666001, 0xc4203ea000)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbf
github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4205b0fb0, 0x3b9aca00, 0xc4203ea000)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4f
github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc4201dc200, 0xc4203ea000)
	/root/go/src/github.com/sk8sio/topic-controller/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x230
created by main.main
	/root/go/src/github.com/sk8sio/topic-controller/cmd/topic-controller.go:99 +0x4b1
```

**Comment by trisberg** [comment]
```
$ k describe po/demo-sk8s-topic-controller-79445c46df-gvq5v
Name:           demo-sk8s-topic-controller-79445c46df-gvq5v
Namespace:      default
Node:           gke-sk8s-demo-18-default-pool-ba7f8119-jln9/10.142.0.6
Start Time:     Thu, 16 Nov 2017 14:13:59 -0500
Labels:         app=sk8s
                component=topic-controller
                pod-template-hash=3500170289
                release=demo
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"demo-sk8s-topic-controller-79445c46df","uid":"4c58df8f-cb02-11e7...
                kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container sk8s-topic-controller
Status:         Running
IP:             10.52.2.13
Created By:     ReplicaSet/demo-sk8s-topic-controller-79445c46df
Controlled By:  ReplicaSet/demo-sk8s-topic-controller-79445c46df
Containers:
  sk8s-topic-controller:
    Container ID:   docker://84581c7b6316bf06ea0f493154a9c8682a25cd7b8e2859568c77b62f07808c2e
    Image:          sk8s/topic-controller:0.0.1-SNAPSHOT.1
    Image ID:       docker-pullable://sk8s/topic-controller@sha256:00ec5e1ab5b6caf1a010433bc7cd7b18fd062bdb565a543d1f8caafc036584ab
    Port:           <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 16 Nov 2017 14:42:39 -0500
      Finished:     Thu, 16 Nov 2017 14:42:39 -0500
    Ready:          False
    Restart Count:  10
    Requests:
      cpu:  100m
    Environment:
      JAVA_TOOL_OPTIONS:                          -Xmx512m
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:   demo-sk8s-kafka:9092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES:  demo-sk8s-zookeeper:2181
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from demo-sk8s-sa-token-9fs84 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  demo-sk8s-sa-token-9fs84:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  demo-sk8s-sa-token-9fs84
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From                                                  Message
  ----     ------                 ----                ----                                                  -------
  Normal   Scheduled              28m                 default-scheduler                                     Successfully assigned demo-sk8s-topic-controller-79445c46df-gvq5v to gke-sk8s-demo-18-default-pool-ba7f8119-jln9
  Normal   SuccessfulMountVolume  28m                 kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  MountVolume.SetUp succeeded for volume "demo-sk8s-sa-token-9fs84"
  Normal   Pulling                25m (x4 over 28m)   kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  pulling image "sk8s/topic-controller:0.0.1-SNAPSHOT.1"
  Normal   Pulled                 25m (x4 over 28m)   kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  Successfully pulled image "sk8s/topic-controller:0.0.1-SNAPSHOT.1"
  Normal   Created                25m (x4 over 28m)   kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  Created container
  Normal   Started                25m (x4 over 28m)   kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  Started container
  Warning  FailedSync             13m (x58 over 26m)  kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  Error syncing pod
  Warning  BackOff                3m (x103 over 26m)  kubelet, gke-sk8s-demo-18-default-pool-ba7f8119-jln9  Back-off restarting failed container
```

**Comment by ericbottard** [comment]
Good news is: seems like I get the same error on minikube.

**Comment by ericbottard** [comment]
This happens when Partitions is `nil`

**Comment by ericbottard** [comment]
Fixed by https://github.com/ericbottard/sk8s-topic-controller/commit/de37af9218a6ade82c427177397b320ba1068393
